POST http://localhost:8000/order/529f2a37-681c-49c5-ba05-e2a8657f5a18/orders
Content-Type: application/json

{
  "productId" : "CATALOG-002"
  , "qty" : 10
  , "unitPrice" : 1000
}

###
GET http://localhost:8000/order/529f2a37-681c-49c5-ba05-e2a8657f5a18/orders


